import type { NextPage } from "next";
import Head from "next/head";
import DashboardNavbar from "../components/main/DashboardNavbar";
import MotivationQuote from "../components/main/MotivationQuote";
import Sidebar from "../components/main/Sidebar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Harmony</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="flex">
          <Sidebar />
          <div className="mx-20 my-14 w-full divide-y">
            <DashboardNavbar />
            <div className="pt-10 w-full flex justify-center">
              <MotivationQuote />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
