import { Button, Typography } from "@mui/material";
import { motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Harmony</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Typography>Hello World</Typography>
        <Button variant="contained" component={motion.div}>
          Here is a button
        </Button>
      </main>
    </>
  );
};

export default Home;
